<h1 align='center'><font color='red'> Task_4


1. [NumPy](#NumPy)
1. [oop](#oop)
3. [ProblemSolving](#ProblemSolving)


<a id='NumPy'></a>
<h1><font color='red'> NumPy

## 1.What does NumPy stand for?


#### A) Number Python
#### B)Numerator Python
#### C) Numerical Python
#### D)There is no full form, it is a stand-alone word  


In [ ]:
A = False #@param {type:"boolean"}
B = False #@param {type:"boolean"}
C = True #@param {type:"boolean"}
D = False #@param {type:"boolean"}


## 2.What does the size attribute in numpy use to find?


#### A) number of items
#### B)shape
#### C) date & time
#### D)unique items
    

In [ ]:
A = True #@param {type:"boolean"}
B = False #@param {type:"boolean"}
C = False #@param {type:"boolean"}
D = False #@param {type:"boolean"}

### 3.What is the purpose of zero() function?

#### A) To create a matrix with the first row and first column as 0
#### B) To create a matrix with diagonal elements as 0
#### C) To create a matrix with all elements as 0
#### D) To return an integer number 0


In [ ]:
A = False #@param {type:"boolean"}
B = False #@param {type:"boolean"}
C = True #@param {type:"boolean"}
D = False #@param {type:"boolean"}

<h1><font color='red'> Answer these question

### 4- create 1D, 2D and 3D arrays in NumPy? then returns the type of the elements stored in the NumPy array.

In [60]:
# One-Dimensional array
import numpy as np
a = np.array([1 , 3 , 5])
a.ndim
a.dtype




numpy.ndarray

In [61]:
# Two-Dimensional array
import numpy as np
b = np.array([[1 , 3 , 5] , [7 , 9 , 11]])
b.ndim
b.dtype






dtype('int64')

In [62]:
# Three-Dimensional array
import numpy as np
c = np.array([[[1 , 5 , 7] , [7 , 9 , 11] , [13 , 15 , 17] ]])
c.ndim
c.dtype






dtype('int64')

### 5-Reverse this array [[[1,2,3,4],[4,5,6,7],[7,8,9,10]]] in two ways......

In [59]:
# Method one
import numpy as np
import array
#arr = np.array([[[1,2,3,4],[4,5,6,7],[7,8,9,10]]]).reshape(4 , 3 , 1 )
#print(arr)
arr = np.array([[[1,2,3,4],[4,5,6,7],[7,8,9,10]]])
arr_rev = arr[::-1 , ::-1 , ::-1]
print(arr_rev)

[[[10  9  8  7]
  [ 7  6  5  4]
  [ 4  3  2  1]]]


In [49]:
# Method two
#>**hint**: use flipud function
import numpy as np
arr = [[[1,2,3,4],[4,5,6,7],[7,8,9,10]]]
np.shape(arr)
np.flipud(arr)




array([[[ 1,  2,  3,  4],
        [ 4,  5,  6,  7],
        [ 7,  8,  9, 10]]])

## 6-Make this array as an array one dimensional

In [3]:
import numpy as np
arr = np.array([[[1,2,3,4],[4,5,6,7],[7,8,9,10]]] , ndmin = 1 )
arr

array([[[ 1,  2,  3,  4],
        [ 4,  5,  6,  7],
        [ 7,  8,  9, 10]]])

## 7- Create a 3X2 integer array and Prints its attributes¶
* Note: The element must be a type of unsigned int16. And print the following Attributes:

- The shape of an array.
- Array dimensions.
- The Length of each element of the array in bytes

In [74]:
arr = np.array([[1 , 2] , [3 , 4] , [5 , 6]] , dtype = np.uint16)
print(arr)
print(arr.shape)
print(arr.ndim)
print(arr.itemsize)


[[1 2]
 [3 4]
 [5 6]]
(3, 2)
2
2


### 8- Return array of odd rows and even columns from below numpy array

* # Ordering the values of each Key and the print the key witht highest value.


> **`sampleArray = numpy.array([[3 ,6, 9, 12], [15 ,18, 21, 24],
[27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])`**


# The output should be:
* `expexted output :
[[ 3  6  9 12]
 [15 18 21 24]
 [27 30 33 36]
 [39 42 45 48]
 [51 54 57 60]]`

* `Printing array of odd rows and even columns
[[ 6 12]
 [30 36]
 [54 60]]`*

In [115]:
import numpy as np
sampleArray = np.array([[3 ,6, 9, 12], [15 ,18, 21, 24], [27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])
#sampleArray[::-1].sort()
#print(sampleArray)
np.sort(sampleArray)[::-1]

array([[51, 54, 57, 60],
       [39, 42, 45, 48],
       [27, 30, 33, 36],
       [15, 18, 21, 24],
       [ 3,  6,  9, 12]])

In [8]:
sampleArray = np.array([[3 ,6, 9, 12], [15 ,18, 21, 24], [27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])
sampleArray

array([[ 3,  6,  9, 12],
       [15, 18, 21, 24],
       [27, 30, 33, 36],
       [39, 42, 45, 48],
       [51, 54, 57, 60]])

In [25]:
sampleArray[0:5:2 ,1:4:2]

array([[ 6, 12],
       [30, 36],
       [54, 60]])

## 9-How is np.mean() different from np.average() in NumPy?

In [ ]:
The np. mean() method returns the arithmetic mean, The numpy. average() function computes the weighted average of elements in an array according to their respective weight given in another array and it returns the algebraic mean if no additional parameters are specificed , np.mean() accepts the dtype argument but np.average() not

## 10-Count the frequency of a given positive value appearing in this NumPy array
## [1, 2, 1, 3, 5, 0, 0, 0, 2, 3] ?

In [27]:
import numpy as np
arr = np.array([1, 2, 1, 3, 5, 0, 0, 0, 2, 3] )
freq = np.unique(arr , return_counts= True)
freq

(array([0, 1, 2, 3, 5]), array([3, 2, 2, 2, 1]))

## 11-Show how is arr[:,0] different from arr[:,[0]]

In [33]:
#in the 1st way we got a single element from the list , in the 2nd way we sliced a list of lists
import numpy as np
arr =np.array([[3 ,6, 9, 12], [15 ,18, 21, 24], [27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])
print(arr[:,0])
print(arr[:,[0]])

[ 3 15 27 39 51]
[[ 3]
 [15]
 [27]
 [39]
 [51]]


### 12-How do you multiply these 2 NumPy array matrices [[15,16,17],[18,19,20],[21,22,23]]  &  [[20,21,22],[23,24,25],[26,27,28]] ?

In [1]:
import numpy as np
arr1 = np.array ([[15,16,17],[18,19,20],[21,22,23]])
arr2 = np.array ([[20,21,22],[23,24,25],[26,27,28]])
arr1*arr2

array([[300, 336, 374],
       [414, 456, 500],
       [546, 594, 644]])

### 13 -Combine these 2 NumPy arrays [1,2,3] & [4,5,6] using vstack()     and hstack()

In [4]:
import numpy as np
a = np.array ( [1,2,3] )
b = np.array ([4,5,6])
print(np.vstack((a , b)))
print(np.hstack((a , b)))

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


# <a id='oop'></a>
<h1><font color='red'> oop

# 1 - a "class" is ... </font>

<br> </br>
#### A) an instance variable
#### B) a code template for creating object
#### C) a function in python
#### D) a synonym for methods

In [ ]:
A = False #@param {type:"boolean"}
B = True #@param {type:"boolean"}
C = False #@param {type:"boolean"}
D = False #@param {type:"boolean"}


# 2- What is a "docstring" ?</font>
<br> </br>
#### A) it is a sting literal specified in source code that is used to explain or document a specific segment of code
#### B) it is a class method that allows working with string documents
#### C) it is an alternative name for instance vaeiables of type string apprearing in classes
#### D) it is a synonym for code comments

In [ ]:
A = True #@param {type:"boolean"}
B = False #@param {type:"boolean"}
C = False #@param {type:"boolean"}
D = True #@param {type:"boolean"}


## 3- Create a Bus class that inherits from the Vehicle class. Give the capacity argument of Bus.seating_capacity() a default value of 50.
- Use the following code for your parent Vehicle class:.
>   class Vehicle:
    def __init__(self, name, max_speed, mileage):
        self.name = name
        self.max_speed = max_speed
        self.mileage = mileage
    def seating_capacity(self, capacity):
        return f"The seating capacity of a {self.name} is {capacity} passengers


In [5]:
class Vehicle:
  def __init__(self , name , max_speed , mileage):
    self.name = name
    self.max_speed = max_speed
    self.mileage = mileage

  def seating_capacity(self, capacity):
      return f"The seating capacity of a {self.name} is {capacity} passengers"


class Bus (Vehicle):
  def seating_capacity(self, capacity = 50):
    return super().seating_capacity(capacity= 50)

# <a id='ProblemSolving'></a>
<h1><font color='red'>Problem Solving


<a href='https://codeforces.com/problemset/problem/339/A'> **problem 1**

In [29]:
# Problem_1 Link:

str = input().split('+')
str.sort()
print('+'.join(str))



1+2
1+2


<a href='https://codeforces.com/problemset/problem/118/A'> **problem 2**

In [27]:
# Problem_2 Link:
str = input().lower()
a = [""]
for i in (str):
  if not i in "aeiouy":
     print((a.append(i)))

     print('.'.join(a))


AHMED
None
.h
None
.h.m
None
.h.m.d


In [31]:
str = input().lower()
a = ".".join([i for i in str if not i in "aeiouy"])
print("." + a)

AHMED
.h.m.d
