<a href="https://colab.research.google.com/github/Rahma0530/IEEE_DS_task/blob/main/Task4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1 align='center'><font color='red'> Task_4


1. [NumPy](#NumPy)
1. [oop](#oop)
3. [ProblemSolving](#ProblemSolving)


<a id='NumPy'></a>
<h1><font color='red'> NumPy

## 1.What does NumPy stand for?


#### A) Number Python
#### B)Numerator Python
#### C) Numerical Python
#### D)There is no full form, it is a stand-alone word  


In [ ]:
A = False #@param {type:"boolean"}
B = False #@param {type:"boolean"}
C = False #@param {type:"boolean"}
D = False #@param {type:"boolean"}


## 2.What does the size attribute in numpy use to find?


#### A) number of items
#### B)shape
#### C) date & time
#### D)unique items
    

In [ ]:
A = False #@param {type:"boolean"}
B = False #@param {type:"boolean"}
C = False #@param {type:"boolean"}
D = False #@param {type:"boolean"}

### 3.What is the purpose of zero() function?

#### A) To create a matrix with the first row and first column as 0
#### B) To create a matrix with diagonal elements as 0
#### C) To create a matrix with all elements as 0
#### D) To return an integer number 0


In [ ]:
A = False #@param {type:"boolean"}
B = False #@param {type:"boolean"}
C = False #@param {type:"boolean"}
D = False #@param {type:"boolean"}

<h1><font color='red'> Answer these question

### 4- create 1D, 2D and 3D arrays in NumPy? then returns the type of the elements stored in the NumPy array.

In [ ]:
# One-Dimensional array







In [ ]:
# Two-Dimensional array







In [ ]:
# Three-Dimensional array








### 5-Reverse this array [[[1,2,3,4],[4,5,6,7],[7,8,9,10]]] in two ways......

In [ ]:
# Method one








In [ ]:
# Method two
#>**hint**: use flipud function







## 6-Make this array as an array one dimensional

## 7- Create a 3X2 integer array and Prints its attributes¶
* Note: The element must be a type of unsigned int16. And print the following Attributes:

- The shape of an array.
- Array dimensions.
- The Length of each element of the array in bytes

### 8- Return array of odd rows and even columns from below numpy array

* # Ordering the values of each Key and the print the key witht highest value.


> **`sampleArray = numpy.array([[3 ,6, 9, 12], [15 ,18, 21, 24],
[27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])`**


# The output should be:
* `expexted output :
[[ 3  6  9 12]
 [15 18 21 24]
 [27 30 33 36]
 [39 42 45 48]
 [51 54 57 60]]`

* `Printing array of odd rows and even columns
[[ 6 12]
 [30 36]
 [54 60]]`*

## 9-How is np.mean() different from np.average() in NumPy?

## 10-Count the frequency of a given positive value appearing in this NumPy array
## [1, 2, 1, 3, 5, 0, 0, 0, 2, 3] ?

## 11-Show how is arr[:,0] different from arr[:,[0]]

### 12-How do you multiply these 2 NumPy array matrices [[15,16,17],[18,19,20],[21,22,23]]  &  [[20,21,22],[23,24,25],[26,27,28]] ?

### 13 -Combine these 2 NumPy arrays [1,2,3] & [4,5,6] using vstack()     and hstack()

# <a id='oop'></a>
<h1><font color='red'> oop

# 1 - a "class" is ... </font>

<br> </br>
#### A) an instance variable
#### B) a code template for creating object
#### C) a function in python
#### D) a synonym for methods

In [ ]:
A = False #@param {type:"boolean"}
B = False #@param {type:"boolean"}
C = False #@param {type:"boolean"}
D = False #@param {type:"boolean"}


# 2- What is a "docstring" ?</font>
<br> </br>
#### A) it is a sting literal specified in source code that is used to explain or document a specific segment of code
#### B) it is a class method that allows working with string documents
#### C) it is an alternative name for instance vaeiables of type string apprearing in classes
#### D) it is a synonym for code comments

In [ ]:
A = False #@param {type:"boolean"}
B = False #@param {type:"boolean"}
C = False #@param {type:"boolean"}
D = False #@param {type:"boolean"}


## 3- Create a Bus class that inherits from the Vehicle class. Give the capacity argument of Bus.seating_capacity() a default value of 50.
- Use the following code for your parent Vehicle class:.
>   class Vehicle:
    def __init__(self, name, max_speed, mileage):
        self.name = name
        self.max_speed = max_speed
        self.mileage = mileage
    def seating_capacity(self, capacity):
        return f"The seating capacity of a {self.name} is {capacity} passengers


# <a id='ProblemSolving'></a>
<h1><font color='red'>Problem Solving


<a href='https://codeforces.com/problemset/problem/339/A'> **problem 1**

In [ ]:
# Problem_1 Link:





<a href='https://codeforces.com/problemset/problem/118/A'> **problem 2**

In [ ]:
# Problem_2 Link:


